### ISSUE TITLE
[Bug]: problem with worldguard

### ISSUE THREAD

**Issue by Gorderok** [Wolfst0rm/ArmorStandEditor-Issues#32] opened 2022-05-10 15:12 UTC
### Expected behavior

blocks interaction with the armor_stand if you are not in the region

### Observed/Actual behavior

There is a problem in 1.18.2 with worldguard protection, in fact any player can interact with all the armor_stand on the server and no longer only those in their region.
I am using worldguard version 7.0.8

### Steps/models to reproduce

use the plugin on a region where you are not on it

### Plugin list

x

### Plugin Version

1.18.2-34.1

### Server Version

1.18.2

**Comment by Wolfieheart** [comment] 2022-05-10 17:23
Could be that this is already fixed with the implementation of Protections in /dev/1.18.2-35, as reproducing there will no longer work. Checking in Master now will see what uncovers

**Comment by Gorderok** [comment] 2022-05-10 20:16
Is this version available? I do not see her

**Comment by Wolfieheart** [comment] 2022-05-10 20:18
If you check the PR that is in draft on the main repository there is a link to the download of Pre2. I am still working on that particular part of the code:

https://github.com/Wolfieheart/ArmorStandEditor/pull/40#issuecomment-1122302465

**Comment by Gorderok** [comment] 2022-05-11 13:03
After testing version 1.18.2-35-Pre 2, it works fine, thank you!

**Comment by Wolfieheart** [comment] 2022-05-11 13:04
Ok that is really useful to know :) 

So the protection works as intended :D Which is a huge win! Thanks for that as well!

**Closed as completed** 2022-05-11 13:12 UTC
Labels: P3: Major, WIP, P5: Tested by Author - FIXED, P0: New Feature Request - Accepted, P2: Implemented, Release: Stable
