### ISSUE TITLE
[Bug]: Can't change / edit lang file

### ISSUE THREAD

**Issue by RhinoCD** [Wolfst0rm/ArmorStandEditor-Issues#33] opened 2022-05-15 01:37 UTC
### Expected behavior

Should be able to edit language file and change its messages

### Observed/Actual behavior

Can't change language file after editing and rebooting server

### Steps/models to reproduce

Edit language file message and reboot server

### Plugin list

-

### Plugin Version

latest

### Server Version

1.18.2

**Comment by Wolfieheart** [comment] 2022-05-15 09:29
OK Checked:

Changing Config Option from one language to the other: Works as Intended
Editing a message to be a different one: Doesnt work for en_US.yml but that is intended (per the comments at the top of that Language File)
```
#This file will be regenerated by the plugin every time the plugin is enabled.
#Do not edit this file. Make a new language file instead.
#Any value not specified in another language file will default to the value listed here.
```

Also tested using nl_NL (as that is the only language I understand externally to en_US) and works as intended. Closed as NAB.

**Closed as completed by Wolfieheart** 2022-05-15 09:29 UTC
Labels: P2: Unable to Reproduce, Release: Stable

**Comment by RhinoCD** [comment] 2022-05-15 23:44
Thank you! Didn't realize that comment aha :)
