### ISSUE TITLE
[Question] Grant permission for invisible itemframes without OP

### ISSUE THREAD

**Issue by Daenges** [Wolfst0rm/ArmorStandEditor-Issues#1] opened 2021-07-24 10:44 UTC
Is there a way to grant the permission for making itemframes invisible without giving players OP directly?

I installed a permission plugin and gave me the "asedit.basic" as requested [here](https://github.com/Wolfst0rm/ArmorStandEditor/blob/master/src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java#L173). But it did not work out and said that I do not have the permission for this, after I had removed OP permissions.

**Comment by Wolfieheart** [comment] 2021-07-24 11:56
Hey, Thanks for asking. 

It appears that I missed something while refactoring. In theory, having `asedit.invisible` would work as well. Will give this a fix in a new build and will test it out :)

**Comment by Wolfieheart** [comment] 2021-07-24 12:00
Fixed in Wolfstorm/ArmorStandEditor@aac13c09999093afccc133d2a30ea8d8dad46439

https://github.com/Wolfst0rm/ArmorStandEditor/commit/aac13c09999093afccc133d2a30ea8d8dad46439 -> for more info :)

**Comment by Daenges** [comment] 2021-07-24 12:01
Thanks alot for this quick response :)

**Comment by Wolfieheart** [comment] 2021-07-24 12:02
Anytime. One additional fix will also be deployed here as well to fix the build :)

**Comment by Wolfieheart** [comment] 2021-07-24 12:13
Alrighty in TestReview. If it passes build will be published soon to Spigot and on the Releases on the main Github :)

**Comment by Daenges** [comment] 2021-07-24 12:14
Perfect :D

**Comment by Wolfieheart** [comment] 2021-07-24 12:29
Fixed and Release is now Available: https://github.com/Wolfst0rm/ArmorStandEditor/releases/tag/1.17.1-28.1

Hotfix also published for a broken permission node :)

**Comment by Daenges** [comment] 2021-07-24 12:50
![Screenshot 2021-07-24 144937](https://user-images.githubusercontent.com/57369924/126868963-35fe98cb-94c0-4a15-8ed9-c753755c956b.png)

Uhm.. Am I doing something wrong?

**Comment by Wolfieheart** [comment] 2021-07-24 13:36
Ermmm that shouldn't be the case. Investigating further. As it is working for players with the following permissions:

![image](https://user-images.githubusercontent.com/18635695/126870114-278746f0-e097-40a6-a66b-289fa7822f18.png)

**Comment by Wolfst0rm** [comment] 2021-07-24 13:39
Do you have a reproduction scenario for this?

**Comment by Wolfieheart** [comment] 2021-07-24 13:52
~~Actually ignore my last comment.~~ I think I know what it is - Setting it to WIP

**Comment by Wolfieheart** [comment] 2021-07-24 13:57
Ok before I go further can you test this version of the Plugin:

Was able to find the exact issue. Was in:  https://github.com/Wolfst0rm/ArmorStandEditor/blob/761ba1aa6a905f6eb8fd207646db01ebc7f7121c/src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java#L149

Link to 1.17.1-28.2: https://cdn.discordapp.com/attachments/817146951014678538/868491946530836540/armorstandeditor-1.17-28.2.jar

Tested it myself and it appears to be working but want to be sure before we go any further :) 

I will probably change the item frames to either stay with `asedit.basic` or change it to `asedit.invisible` in the future :)

**Comment by Daenges** [comment] 2021-07-24 15:45
@Wolfst0rm Tested it out. It works perfectly fine! :D 
Only thing is that the item in the frame is turning if you make it invisible.

**Comment by Wolfieheart** [comment] 2021-07-24 15:58
Hrmmm might not be able to prevent that since that's a vanilla thing.  Unless we wrap an OnInteractEvent through it to stop it, but that's for later :D 

Thank you very much for testing it btw!

**Closed as completed by Wolfieheart** 2021-07-24 15:58 UTC
Labels: bug, good first issue, question, P3: Major, P5: Tested by Author - FIXED
