### ISSUE TITLE
[Bug]: PlayerInteractAtEntityEvent fired twice

### ISSUE THREAD

**Issue by Tiippex** [Wolfst0rm/ArmorStandEditor-Issues#27] opened 2022-02-06 13:27 UTC
### Expected behavior

Interacting with an armor stand should fire the PlayerInteractAtEntityEvent only once. With ASEReborn it fires twice.

### Observed/Actual behavior

Interacting with armor stands fires with ASEReborn the PlayerInteractAtEntityEvent twice. Disabling the plugins fixes the problem.

### Steps/models to reproduce

Simply place the plugin in the plugin folder and add some debug messages in the PlayerInteractAtEntityEvent:

```
    @EventHandler
    public void onClick(PlayerInteractAtEntityEvent event) {
        Entity entity = event.getRightClicked();
        if (!(entity instanceof ArmorStand)) return;

        System.out.println("PlayerInteractAtEntityEvent: " + event.getPlayer());
    }
```
 

### Plugin list

ArmorStandEditorReborn
WorldEdit
WorldGuard
ASETest (My plugin to debug the event)

### Plugin Version

1.18.1-33

### Server Version

paper 1.18.1 Build 187

**Comment by Wolfieheart** [comment] 2022-02-23 19:17
Investigating - Sorry for the delay with this. House Move was and still is chaotic and I have a general MC burnout :)

**Comment by Wolfieheart** [comment] 2022-02-23 19:27
Confirmed and noticing the same for ItemFrames. Fix WIP

**Comment by Wolfieheart** [comment] 2022-02-23 19:34
Caused by the events.add on 

https://github.com/Wolfieheart/ArmorStandEditor/blob/1b2595bf856175d79440bd2244ea44ddaa95e272/src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java#L281
&
https://github.com/Wolfieheart/ArmorStandEditor/blob/master/src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java#L305

**Comment by Wolfieheart** [comment] 2022-02-23 19:46
Ready for testing. You can find the dev build on: https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/1889343312

Please download the artifact.zip and change over the plugin to match.

NOTE: For now it is still reporting as 1.18.1-33. If confirmed fix, then I will also do a minor version increment.

**Comment by Tiippex** [comment] 2022-02-23 21:39
Hey,

the fix looks great. It's working well :)

**Comment by Wolfieheart** [comment] 2022-02-24 08:41
Marking as fixed and version bumping. Full Deployment of 1.18.1-33.1 will be soon TM

**Comment by Wolfieheart** [comment] 2022-02-24 08:41
Also Thanks for the Help Max/Tiippex! Thanks for being patient and testing the hotfix :)

**Closed as completed** 2022-02-25 10:04 UTC
Labels: P2: Able to Reproduce, P3: Minor, P5: Tested by Author - FIXED, P2: Implemented
