### ISSUE TITLE
[Bug]: Toggling item frame visibility places flint inside.

### ISSUE THREAD

**Issue by mibby** [Wolfst0rm/ArmorStandEditor-Issues#25] opened 2022-01-07 07:48 UTC
### Expected behavior

Just toggle item frame, don't put item inside it as well.

### Observed/Actual behavior

Flint goes inside armor stand when made invisible.

### Steps/models to reproduce

* Enable item frame invisibility toggle
* Right click item frame with flint
* Flint goes in armorstand

https://streamable.com/q5gysg

### Plugin list

Irrelevant.

### Plugin Version

https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/1664854844

### Server Version

Purpur dev 1495 (Paper 1.18.1)

### Other

Is it possible to cancel the placement event when interacting with flint while it is trying to toggle the state of the entity / tile?

**Comment by Wolfieheart** [comment] 2022-01-08 21:21
Duplicate of #3

**Closed as completed by Wolfieheart** 2022-01-08 21:21 UTC
Labels: invalid
